---
apiVersion: v1
	kind: Service
	metadata:
	    name: expose-prometheus
	spec:
	    selector:
	        env: monitorSys
	    type: NodePort
	    ports:
	        -   nodePort: 30000
	            port: 9099

	            targetPort: 9090
              
---
apiVersion: v1
	kind: PersistentVolumeClaim
	metadata:
	    name: prometheus-volume
	    labels:
	        name: prometheus-volume
	spec:
	    accessModes:
	        -   ReadWriteOnce
	    resources:
	        requests:
	            storage: 10Gi 
---
kind: ConfigMap
	apiVersion: v1
	metadata:
	  name: prometheus-config
	data:
	  prometheus.yml: |
	    global:
	      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
	      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute..
	      
	    scrape_configs:
	      - job_name: 'prometheus'
	        static_configs:
	        - targets: ['localhost:9090']
	      - job_name: 'node'
	        static_configs:
	        - targets: ['192.168.29.187:9100']
	          
              labels:
                 env: 'monitorSys'
 ---
 apiVersion: apps/v1
	kind: Deployment
	metadata:
	  name: prometheus-deploy
	spec:
	    replicas: 1
	    selector: 
	        matchLabels:
	            env: monitorSys
	      
	    template:
	        metadata: 
	            name: prometheus-deploy
	            labels:
	                env: monitor-Sys
	        spec: 
	            containers: 
	            -   name: prometheus-container
	                image: kunal8/prometheus:1
	                volumeMounts:
	                    -   name: prometheus-vol
	                        mountPath: /etc/prometheus/data
	                    -   name: prometheus-config
	                        mountPath: /etc/prometheus/prometheus.yml
	                        subPath: prometheus.yml  
	            volumes:
	                -   name: prometheus-vol
	                    persistentVolumeClaim:
	                        claimName: prometheus-volume
	                -   name: prometheus-config
	                    configMap:
	                        name: prometheus-config

  	                        defaultMode: 0744
